name: 'Check coverage increased'
description: 'Check if coverage source is greater than target'
icon: 'check'
color: 'green'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'